import { chromium } from 'playwright';
const dir='/tmp/claude-0/-home-user-LighterSim/cf51c021-eccd-5a3d-afe4-844decbebd1f/scratchpad/';
const browser = await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
const p = await browser.newPage({viewport:{width:320,height:568},deviceScaleFactor:2,hasTouch:true});
await p.goto('http://localhost:8741/index.html');
await p.waitForFunction(()=>window.__booted && LIGHTER.frames>10,null,{timeout:60000});
await p.evaluate(()=>LIGHTER.openLid());
await p.waitForFunction(()=>LIGHTER.lidOpen(),null,{timeout:8000});
await p.evaluate(()=>LIGHTER.svcOut());
await p.waitForTimeout(2500);
const r = await p.evaluate(()=>{const h=document.getElementById('hint').getBoundingClientRect(),d=document.getElementById('svcDone').getBoundingClientRect();return {hint:document.getElementById('hint').textContent,h:{y:h.y,b:h.bottom,w:h.width,ht:h.height},d:{y:d.y,b:d.bottom},overlap:h.y<d.bottom};});
console.log(JSON.stringify(r));
await p.screenshot({path:dir+'svc_320.png'});
await browser.close();
